# Generated by Django 5.1.5 on 2025-03-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('revenue', models.FloatField(default=0.0)),
                ('profit', models.FloatField(default=0.0)),
                ('employees', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'business',
            },
        ),
    ]
