"""
Django settings for orm1 project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os 
#import dj_database_url
import pymysql
pymysql.install_as_MySQLdb()
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.

#CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite React URL
    "https://616b-2601-cb-8200-61c0-f547-8d04-27f4-4b4e.ngrok-free.app",
     "https://djangoappcontainer2025unique.azurewebsites.net"
    
]
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS =True



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-)pt8y2inum55@8lr#w%d_0u8ikhl6h^ogje(=l!p4=ur--it=0'

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY','django-insecure-)pt8y2inum55@8lr#w%d_0u8ikhl6h^ogje(=l!p4=ur--it=0')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =  'True'


ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = ["https://616b-2601-cb-8200-61c0-f547-8d04-27f4-4b4e.ngrok-free.app",
                        "https://djangoappcontainer2025unique.azurewebsites.net",
                       "https://etl-backend-django-ghezfnb8b6ebcrcw.eastus2-01.azurewebsites.net"]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'orm2',
    'rest_framework',
    'corsheaders'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
       
]

MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = 'orm1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'orm1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#DATABASE_URL = os.getenv('DATABASE_URL')
DJANGO_SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

import os
import base64



ssl_cert = os.getenv('PG_SSLROOTCERT', None)  # Fetch Base64 encoded cert from env
cert_path = "/tmp/azure_postgres_root.pem"

if ssl_cert:
    try:
        # Decode from Base64 and write to a .pem file
        with open(cert_path, "wb") as cert_file:
            cert_file.write(base64.b64decode(ssl_cert))
        print(f"✅ SSL certificate written to {cert_path}")
    except Exception as e:
        print(f"❌ Error writing SSL cert: {e}")
else:
    print("⚠ No SSL certificate found in environment variables.")

#DATABASES = {
 #   'default': {
  #      'ENGINE': 'django.db.backends.postgresql',
   #     'NAME': 'postgres',  # Replace with your actual database name
    #    'USER': 'sowji',  # Your PostgreSQL username
     #   'PASSWORD': 'Sairam#123',  # Your PostgreSQL password
      #  'HOST': 'etlpostgre.postgres.database.azure.com',  # Your Azure PostgreSQL host
       # 'PORT': '5432',  # Default PostgreSQL port
        # 'OPTIONS': {
         #   'sslmode': 'require',  # Disabling SSL encryption
           
        #},
    #}
#}
#DATABASES = {
 #   'default': {
  #      'ENGINE': 'django.db.backends.mysql',
   #     'NAME': 'postgres',  # Replace with your actual database name
    #    'USER': 'sowji',  # Your PostgreSQL username
     #   'PASSWORD': 'Sairam#123',  # Your PostgreSQL password
      #  'HOST': 'etlsql.mysql.database.azure.com',  # Your Azure PostgreSQL host
       # 'PORT': '3306',  # Default PostgreSQL port
        
    #}
#}





DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # The database file
    }
}




# ✅ Use Azure PostgreSQL Database
#DATABASES = {
 #   'default': dj_database_url.config(default=os.getenv("DATABASE_URL"))
#}
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
